version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "8084:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coffee-shop
    networks:
      springboot-mysql-net:

  server:
    container_name: server
    build:
      context: ./server/coffeeshop/
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

  client:
    container_name: client
    build:
      context: ./client/coffee-shop/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure
networks:
  springboot-mysql-net:


