version: "3.3"

services:

  eureka-server:
    container_name: eureka-server
    build:
      context: ./server-eureka/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      coffee-net:
    restart: on-failure

#  order-service:
#    container_name: order-service
#    build:
#      context: ./order/
#      dockerfile: Dockerfile
#    networks:
#      coffee-net:
#    restart: on-failure


  gateway-service:
    container_name: gateway-service
    build:
      context: ./gatewayservice/
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      coffee-net:
    restart: on-failure

  config-server:
    container_name: config-server
    build:
      context: ./config-server/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      coffee-net:
    restart: on-failure


  core-service:
    container_name: core-service
    build:
      context: ./server/coffeeshop/
      dockerfile: Dockerfile
    networks:
      coffee-net:
    restart: on-failure

  client:
    container_name: client
    build:
      context: ./client/coffee-shop/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      coffee-net:
    restart: on-failure

networks:
  coffee-net:


