export enum CookieLimitName {
  LIMIT_PRODUCT = "limitProducts",
  LIMIT_CUSTOMER = "limitCustomers",
  LIMIT_CUSTOMER_GROUP = "limitCustomerGroups",
  LIMIT_VARIANT = "limitVariants",
  LIMIT_COMPOSITES = "limitComposites",
  LIMIT_NATIONAL_DRUG_CATEGORIES = "limit_national_drug_categories",
  LIMIT_CAMPAIGN_MARKETING = "limit_campaign_marketings",
  LIMIT_PACKSIZE = "limitPacksizes",
  LIMIT_SERIAL = "limitSerials",
  LIMIT_CATEGORY = "limitCategories",
  LIMIT_LOTS_DATE = "limitLotsDate",
  LIMIT_ORDER_RETURN = "limitOrderReturns",
  LIMIT_ORDER = "limitOrdersV2",
  LIMIT_SHIPMENT = "limitShipments",
  LIMIT_EINVOICE = "limitEInvoices",
  LIMIT_SHIPMENT_HANDOVER = "limitShipmentsHanover",
  LIMIT_DELIVERY_COLLATIONS = "limitDeliveryCollations",
}
